-- AlterTable
ALTER TABLE "companies" ADD COLUMN     "ai_auto_approve" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "ai_confidence_threshold" DOUBLE PRECISION,
ADD COLUMN     "ai_context" TEXT,
ADD COLUMN     "business_model" TEXT,
ADD COLUMN     "chart_of_accounts" TEXT,
ADD COLUMN     "cost_centers_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "employee_count" INTEGER,
ADD COLUMN     "fiscal_year_start" INTEGER,
ADD COLUMN     "founded_at" TIMESTAMP(3),
ADD COLUMN     "industry" TEXT,
ADD COLUMN     "language" VARCHAR(5) DEFAULT 'de',
ADD COLUMN     "legal_form" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "projects_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "status" TEXT DEFAULT 'active',
ADD COLUMN     "sub_industry" TEXT,
ADD COLUMN     "timezone" TEXT DEFAULT 'Europe/Zurich',
ADD COLUMN     "uid_number" TEXT,
ADD COLUMN     "vat_flat_rate" DOUBLE PRECISION,
ADD COLUMN     "vat_interval" TEXT,
ADD COLUMN     "vat_liable" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "vat_method" TEXT,
ADD COLUMN     "website" TEXT;
